/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace keystroke {
    export interface KeyPress {
        value?: string;
        pressDuration?: number;
        waitDuration?: number;
        shift?: boolean;
        ctrl?: boolean;
        alt?: boolean;
        meta?: boolean;
    }
    export interface TrainStats {
        samples?: number;
        finalLoss?: number;
        minLoss?: number;
        maxLoss?: number;
        avgLoss?: number;
        stdLoss?: number;
    }
    export interface Attempt {
        keyPresses?: keystroke.KeyPress[];
    }
    export interface TrainRequest {
        attempts?: keystroke.Attempt[];
        email?: string;
    }
    export interface TrainResponse {
        message?: string;
        stats?: keystroke.TrainStats;
        id?: string;
    }
    export interface KeystrokeService {
        train(
            data: TrainRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<TrainResponse>;
    }
}

